import bcrypt from "bcryptjs";
import mongoose from "mongoose";
import { connectDatabase } from "../src/config/database.js";
import { User } from "../src/models/User.js";
import { Course } from "../src/models/Course.js";
import { Task } from "../src/models/Task.js";
import { Group } from "../src/models/Group.js";
import { HelpTopic } from "../src/models/HelpTopic.js";

async function run() {
  await connectDatabase();

  await Promise.all([
    User.deleteMany({}),
    Course.deleteMany({}),
    Task.deleteMany({}),
    Group.deleteMany({}),
    HelpTopic.deleteMany({}),
  ]);

  const passwordHash = await bcrypt.hash("password123", 10);
  const user = await User.create({
    name: "Student User",
    email: "student@university.edu",
    passwordHash,
    unreadMessages: 2,
    accountStatus: "Active",
    settings: [
      "Notification Preferences",
      "Display Settings",
      "Privacy & Security",
      "Language & Region",
    ],
  });

  await Course.insertMany([
    {
      userId: user._id,
      courseName: "Applied Modern Algebra",
      courseCode: "PHSC 114",
      term: "Spring 2026",
      thumbnail: "red",
      announcements: 2,
      discussions: 3,
      files: 5,
      latestAnnouncement: {
        title: "HW 04 Now Available",
        preview: "The fourth homework assignment covering chapters 5-6 is now available.",
        date: "Feb 15, 2026",
      },
      announcementFeed: [
        { title: "HW 04 Now Available", preview: "The fourth homework assignment covering chapters 5-6 is now available.", date: "Feb 15, 2026" },
        { title: "Quiz 2 Review Session", preview: "Join the review session in PHSC 201 at 4:00 PM this Thursday.", date: "Feb 12, 2026" },
      ],
      discussionThreads: [
        { title: "Week 5 Proof Techniques", replies: 6, updatedAtLabel: "2h ago" },
        { title: "Homework 3 Clarifications", replies: 4, updatedAtLabel: "1d ago" },
        { title: "Exam Strategy Thread", replies: 9, updatedAtLabel: "2d ago" },
      ],
      recentFiles: [
        { name: "Lecture_05_Notes.pdf", uploadedAtLabel: "Uploaded 1d ago" },
        { name: "HW04_Rubric.pdf", uploadedAtLabel: "Uploaded 2d ago" },
        { name: "Practice_Set_B.docx", uploadedAtLabel: "Uploaded 3d ago" },
      ],
      focused: true,
      gradePercent: 92,
      assignmentsDue: 3,
      upcomingEvents: 2,
      nextExamIn: "5 days",
    },
    {
      userId: user._id,
      courseName: "Computer Science Foundations",
      courseCode: "C S-4063-001",
      term: "Spring 2026",
      thumbnail: "green",
      announcements: 1,
      discussions: 5,
      files: 8,
      latestAnnouncement: {
        title: "Lab 2 Teams Finalized",
        preview: "Team assignments are now posted. Check your section group list.",
        date: "Feb 14, 2026",
      },
      announcementFeed: [
        { title: "Lab 2 Teams Finalized", preview: "Team assignments are now posted. Check your section group list.", date: "Feb 14, 2026" },
        { title: "Midterm Topics Released", preview: "The exam will cover modules 1-4 and recursion fundamentals.", date: "Feb 10, 2026" },
      ],
      discussionThreads: [
        { title: "Project Proposal QA", replies: 11, updatedAtLabel: "45m ago" },
        { title: "Recursion Practice Problems", replies: 7, updatedAtLabel: "6h ago" },
        { title: "Office Hours Requests", replies: 3, updatedAtLabel: "1d ago" },
      ],
      recentFiles: [
        { name: "Lab2_Starter_Code.zip", uploadedAtLabel: "Uploaded 4h ago" },
        { name: "Midterm_Study_Guide.pdf", uploadedAtLabel: "Uploaded 1d ago" },
        { name: "Section_Slides_Week4.pptx", uploadedAtLabel: "Uploaded 2d ago" },
      ],
      gradePercent: 88,
      assignmentsDue: 2,
      upcomingEvents: 4,
      nextExamIn: "12 days",
    },
    {
      userId: user._id,
      courseName: "Data Structures & Algorithms",
      courseCode: "CS-3345-002",
      term: "Spring 2026",
      thumbnail: "blue",
      announcements: 3,
      discussions: 2,
      files: 12,
      latestAnnouncement: {
        title: "Tree Traversal Worksheet",
        preview: "A new worksheet on BST traversals has been posted in Files.",
        date: "Feb 13, 2026",
      },
      announcementFeed: [
        { title: "Tree Traversal Worksheet", preview: "A new worksheet on BST traversals has been posted in Files.", date: "Feb 13, 2026" },
        { title: "Sorting Lab Open", preview: "Submit your merge sort implementation by Sunday night.", date: "Feb 11, 2026" },
      ],
      discussionThreads: [
        { title: "AVL Rotations Visual Guide", replies: 5, updatedAtLabel: "3h ago" },
        { title: "Complexity Analysis Thread", replies: 8, updatedAtLabel: "10h ago" },
      ],
      recentFiles: [
        { name: "BST_Practice_Set.pdf", uploadedAtLabel: "Uploaded 8h ago" },
        { name: "Sorting_Lab_Instructions.pdf", uploadedAtLabel: "Uploaded 1d ago" },
        { name: "Complexity_Cheat_Sheet.png", uploadedAtLabel: "Uploaded 2d ago" },
      ],
      gradePercent: 84,
      assignmentsDue: 4,
      upcomingEvents: 1,
      nextExamIn: "18 days",
    },
    {
      userId: user._id,
      courseName: "Database Management Systems",
      courseCode: "CS-4347-001",
      term: "Spring 2026",
      thumbnail: "purple",
      announcements: 0,
      discussions: 1,
      files: 6,
      latestAnnouncement: {
        title: "ER Diagram Workshop",
        preview: "Bring your schema drafts for feedback in Friday's workshop.",
        date: "Feb 12, 2026",
      },
      announcementFeed: [
        { title: "ER Diagram Workshop", preview: "Bring your schema drafts for feedback in Friday's workshop.", date: "Feb 12, 2026" },
      ],
      discussionThreads: [
        { title: "Normalization Examples", replies: 2, updatedAtLabel: "1d ago" },
      ],
      recentFiles: [
        { name: "ERD_Template.drawio", uploadedAtLabel: "Uploaded 12h ago" },
        { name: "Schema_Design_Checklist.pdf", uploadedAtLabel: "Uploaded 2d ago" },
        { name: "SQL_Practice_Set_1.sql", uploadedAtLabel: "Uploaded 3d ago" },
      ],
      gradePercent: 91,
      assignmentsDue: 1,
      upcomingEvents: 3,
      nextExamIn: "9 days",
    },
  ]);

  await Task.insertMany([
    {
      userId: user._id,
      section: "today",
      dateLabel: "February 15",
      eventDate: "2026-02-15",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Project Proposal",
      taskType: "assignment",
      points: 10,
      dueTime: "11:59 PM",
      checked: true,
      thumbnail: "green",
    },
    {
      userId: user._id,
      section: "tomorrow",
      dateLabel: "Tomorrow, February 16",
      eventDate: "2026-02-16",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Applied Modern Algebra Lecture",
      taskSubtitle: "PHSC 114",
      taskType: "calendar",
      time: "9:00 AM to 9:50 AM",
      thumbnail: "red",
      thumbnailLabel: "APPLIED MODERN ALGEBRA - SPRING 2026",
    },
    {
      userId: user._id,
      section: "tomorrow",
      dateLabel: "Tomorrow, February 16",
      eventDate: "2026-02-16",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Applied Modern Algebra Office Hours",
      taskSubtitle: "PHSC 1121",
      taskType: "calendar",
      time: "10:00 AM to 11:00 AM",
      thumbnail: "red",
      thumbnailLabel: "APPLIED MODERN ALGEBRA - SPRING 2026",
    },
    {
      userId: user._id,
      section: "tomorrow",
      dateLabel: "Tomorrow, February 16",
      eventDate: "2026-02-16",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 ASSIGNMENT",
      taskTitle: "HW 03",
      taskType: "assignment",
      points: 5,
      checked: true,
      thumbnail: "red",
      thumbnailLabel: "",
    },
    // --- April 30 & May 2026 (calendar + assignments across courses) ---
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "April 30, 2026",
      eventDate: "2026-04-30",
      courseCode: "PHSC 114",
      courseName: "PHSC 114 - Applied Modern Algebra - Spring 2026",
      taskTitle: "Final problem set",
      taskType: "assignment",
      points: 40,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "April 30, 2026",
      eventDate: "2026-04-30",
      courseCode: "PHSC 114",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Exam review session",
      taskType: "calendar",
      time: "3:00 PM to 4:30 PM",
      thumbnail: "red",
      thumbnailLabel: "PHSC 114",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "April 30, 2026",
      eventDate: "2026-04-30",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - SPRING 2026 ASSIGNMENT",
      taskTitle: "HCI prototype checkpoint",
      taskType: "assignment",
      points: 25,
      dueTime: "5:00 PM",
      checked: false,
      thumbnail: "green",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 1, 2026",
      eventDate: "2026-05-01",
      courseCode: "CS-3345-002",
      courseName: "CS-3345-002 - Data Structures - Spring 2026",
      taskTitle: "Binary search tree lab",
      taskType: "assignment",
      points: 15,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "blue",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 1, 2026",
      eventDate: "2026-05-01",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Lecture: rings and ideals",
      taskType: "calendar",
      time: "9:00 AM to 9:50 AM",
      thumbnail: "red",
      thumbnailLabel: "PHSC 114",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 3, 2026",
      eventDate: "2026-05-03",
      courseCode: "CS-4347-001",
      courseName: "CS-4347-001 - Database Systems - Spring 2026",
      taskTitle: "ER diagram draft",
      taskType: "assignment",
      points: 20,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "purple",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 4, 2026",
      eventDate: "2026-05-04",
      courseCode: "PHSC 114",
      courseName: "PHSC 114 - Applied Modern Algebra",
      taskTitle: "Quiz 5 (take-home)",
      taskType: "assignment",
      points: 10,
      dueTime: "8:00 AM",
      checked: true,
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 5, 2026",
      eventDate: "2026-05-05",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Team standup (online)",
      taskType: "calendar",
      time: "2:00 PM to 2:30 PM",
      thumbnail: "green",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 6, 2026",
      eventDate: "2026-05-06",
      courseCode: "PHSC 114",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 ASSIGNMENT",
      taskTitle: "Homework 12",
      taskType: "assignment",
      points: 12,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 6, 2026",
      eventDate: "2026-05-06",
      courseCode: "CS-3345-002",
      courseName: "CS-3345-002 - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Recitation: heaps",
      taskType: "calendar",
      time: "4:00 PM to 5:15 PM",
      thumbnail: "blue",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 8, 2026",
      eventDate: "2026-05-08",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - Computer Science Foundations",
      taskTitle: "Reading response #8",
      taskType: "assignment",
      points: 5,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "green",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 9, 2026",
      eventDate: "2026-05-09",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Study group (library)",
      taskType: "calendar",
      time: "6:00 PM to 8:00 PM",
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 10, 2026",
      eventDate: "2026-05-10",
      courseCode: "CS-4347-001",
      courseName: "CS-4347-001 - SPRING 2026 ASSIGNMENT",
      taskTitle: "SQL practice set 4",
      taskType: "assignment",
      points: 18,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "purple",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 11, 2026",
      eventDate: "2026-05-11",
      courseCode: "PHSC 114",
      courseName: "PHSC 114 - Applied Modern Algebra - Spring 2026",
      taskTitle: "Proof workshop prep",
      taskType: "assignment",
      points: 8,
      dueTime: "10:00 AM",
      checked: false,
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 12, 2026",
      eventDate: "2026-05-12",
      courseCode: "PHSC 114",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Final exam (in person)",
      taskType: "calendar",
      time: "8:00 AM to 10:00 AM",
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 12, 2026",
      eventDate: "2026-05-12",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Course reflection essay",
      taskType: "assignment",
      points: 15,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "green",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 14, 2026",
      eventDate: "2026-05-14",
      courseCode: "CS-3345-002",
      courseName: "CS-3345-002 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Graph algorithms problem set",
      taskType: "assignment",
      points: 22,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "blue",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 15, 2026",
      eventDate: "2026-05-15",
      courseCode: "CS-3345-002",
      courseName: "CS-3345-002 - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Office hours (extra)",
      taskType: "calendar",
      time: "1:00 PM to 3:00 PM",
      thumbnail: "blue",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 16, 2026",
      eventDate: "2026-05-16",
      courseCode: "CS-4347-001",
      courseName: "CS-4347-001 - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Project demo dry run",
      taskType: "calendar",
      time: "10:00 AM to 12:00 PM",
      thumbnail: "purple",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 17, 2026",
      eventDate: "2026-05-17",
      courseCode: "PHSC 114",
      courseName: "Applied Modern Algebra - Spring 2026",
      taskTitle: "Extra credit worksheet",
      taskType: "assignment",
      points: 5,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 18, 2026",
      eventDate: "2026-05-18",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Final presentations block A",
      taskType: "calendar",
      time: "9:00 AM to 12:00 PM",
      thumbnail: "green",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 19, 2026",
      eventDate: "2026-05-19",
      courseCode: "CS-4347-001",
      courseName: "CS-4347-001 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Normalization quiz",
      taskType: "assignment",
      points: 12,
      dueTime: "11:59 PM",
      checked: true,
      thumbnail: "purple",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 20, 2026",
      eventDate: "2026-05-20",
      courseCode: "CS-3345-002",
      courseName: "CS-3345-002 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Dynamic programming challenge",
      taskType: "assignment",
      points: 30,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "blue",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 21, 2026",
      eventDate: "2026-05-21",
      courseName: "APPLIED MODERN ALGEBRA - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Course wrap-up Q&A",
      taskType: "calendar",
      time: "2:00 PM to 3:00 PM",
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 22, 2026",
      eventDate: "2026-05-22",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Peer review comments due",
      taskType: "assignment",
      points: 8,
      dueTime: "5:00 PM",
      checked: false,
      thumbnail: "green",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 23, 2026",
      eventDate: "2026-05-23",
      courseCode: "CS-4347-001",
      courseName: "CS-4347-001 - Database Management Systems",
      taskTitle: "Transaction lab",
      taskType: "assignment",
      points: 16,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "purple",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 25, 2026",
      eventDate: "2026-05-25",
      courseCode: "CS-3345-002",
      courseName: "CS-3345-002 - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Memorial Day — no lecture",
      taskType: "calendar",
      time: "All day",
      thumbnail: "blue",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 26, 2026",
      eventDate: "2026-05-26",
      courseCode: "PHSC 114",
      courseName: "PHSC 114 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Portfolio submission",
      taskType: "assignment",
      points: 50,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "red",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 27, 2026",
      eventDate: "2026-05-27",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Final presentations block B",
      taskType: "calendar",
      time: "1:00 PM to 4:00 PM",
      thumbnail: "green",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 28, 2026",
      eventDate: "2026-05-28",
      courseCode: "CS-3345-002",
      courseName: "CS-3345-002 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Final exam review packet",
      taskType: "assignment",
      points: 0,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "blue",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 29, 2026",
      eventDate: "2026-05-29",
      courseCode: "CS-4347-001",
      courseName: "CS-4347-001 - SPRING 2026 ASSIGNMENT",
      taskTitle: "Final project report",
      taskType: "assignment",
      points: 40,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "purple",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 30, 2026",
      eventDate: "2026-05-30",
      courseCode: "CS-3345-002",
      courseName: "CS-3345-002 - SPRING 2026 CALENDAR EVENT",
      taskTitle: "Final exam (cumulative)",
      taskType: "calendar",
      time: "10:30 AM to 12:30 PM",
      thumbnail: "blue",
    },
    {
      userId: user._id,
      section: "upcoming",
      dateLabel: "May 31, 2026",
      eventDate: "2026-05-31",
      courseCode: "C S-4063-001",
      courseName: "C S-4063-001 - SPRING 2026 ASSIGNMENT",
      taskTitle: "End-of-semester survey",
      taskType: "assignment",
      points: 2,
      dueTime: "11:59 PM",
      checked: false,
      thumbnail: "green",
    },
  ]);

  await Group.insertMany([
    { userId: user._id, name: "Algebra Study Group", members: 8, course: "PHSC 114", lastActive: "2 hours ago", color: "var(--dashboard-accent-red)" },
    { userId: user._id, name: "CS Foundations Lab Team", members: 4, course: "C S-4063-001", lastActive: "5 hours ago", color: "var(--dashboard-accent-green)" },
    { userId: user._id, name: "Data Structures Review", members: 12, course: "CS-3345-002", lastActive: "1 day ago", color: "var(--dashboard-info)" },
    { userId: user._id, name: "Database Project Team", members: 3, course: "CS-4347-001", lastActive: "3 days ago", color: "#8b5cf6" },
  ]);

  await HelpTopic.insertMany([
    { title: "Getting Started", description: "Learn the basics of navigating your dashboard and courses", color: "var(--dashboard-info)" },
    { title: "Submitting Assignments", description: "How to upload and submit your coursework on time", color: "var(--dashboard-success)" },
    { title: "Messaging & Discussions", description: "Communicate with instructors and classmates", color: "var(--dashboard-warning)" },
    { title: "Technical Support", description: "Troubleshoot common issues and contact support", color: "var(--dashboard-accent-red)" },
  ]);

  console.log("Seeded data.");
  await mongoose.connection.close();
}

run().catch(async (error) => {
  console.error(error);
  await mongoose.connection.close();
  process.exit(1);
});
